# Generated by Django 3.2 on 2023-08-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_linea_pedido_lineapedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='linea_pedido',
        ),
    ]
