# Generated by Django 3.2 on 2023-08-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_delete_linea_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineaPedido',
        ),
    ]
